parameters:
    domain: "legacydental.net"
    recursive_depth: 1
    link_limit: 10
    
    file_extractors:
      js:
        limit: 10
        regex: ""

      css:
        limit: 10
        regex: ""

log_level: 'INFO'